DROP TABLE IF EXISTS notifications.notification_audit;
DROP TABLE IF EXISTS notifications.notification_preferences;
DROP TABLE IF EXISTS notifications.user_notifications;
DROP TABLE IF EXISTS notifications.messages;
DROP TABLE IF EXISTS notifications.notifications;
DROP TABLE IF EXISTS notifications.subscriptions;
DROP TABLE IF EXISTS notifications.topics;
DROP TABLE IF EXISTS notifications.users;
DROP SCHEMA IF EXISTS notifications;
