version: '3'

networks:
  api-tests:
    driver: bridge

services:
  # Test Container for running tests locally
  local_tests:
    env_file:
      - DockerfileTest.env
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - pennsievedb
      - dynamodb    
    volumes:
      - $PWD:/go/src/github.com/pennsieve/integration-service
    networks:
      - api-tests

    # Test Container for running tests on CI
  ci_tests:
    env_file:
      - DockerfileTestCI.env
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - pennsievedb-ci
      - dynamodb-ci
    volumes:
      - $PWD:/go/src/github.com/pennsieve/integration-service
    networks:
      - api-tests

  pennsievedb:
    image: pennsieve/pennsievedb:V20230531145242-seed
    container_name: pennsievedb
    restart: always
    ports:
      - "5432:5432"
    networks:
      - api-tests

  pennsievedb-ci:
    image: pennsieve/pennsievedb:V20230531145242-seed
    restart: always
    networks:
      - api-tests
      
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    volumes:
      - ./test-dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    networks:
      - api-tests

  dynamodb-ci:
    image: amazon/dynamodb-local
    restart: always
    volumes:
      - ./test-dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    networks:
      - api-tests    