version: '3'

networks:
  api-tests:
    driver: bridge

services:
  # Test Container for running tests locally
  local_tests:
    env_file:
      - DockerfileTest.env
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - pennsievedb     
    volumes:
      - $PWD:/go/src/github.com/pennsieve/integration-service
    networks:
      - api-tests

    # Test Container for running tests on CI
  ci_tests:
    env_file:
      - DockerfileTestCI.env
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - pennsievedb-ci
    volumes:
      - $PWD:/go/src/github.com/pennsieve/integration-service
    networks:
      - api-tests


  pennsievedb:
    image: pennsieve/pennsievedb:V20230531145242-seed
    container_name: pennsievedb
    restart: always
    ports:
      - "5432:5432"
    networks:
      - api-tests

  pennsievedb-ci:
    image: pennsieve/pennsievedb:V20230531145242-seed
    restart: always
    networks:
      - api-tests      